---
title: "My Website"
description: |
  Herzlich Willkommen zu Netflix Webseite!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

```{r}
library(tidyverse)

netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')  %>% 
  separate(duration, c("duration", "duration_units"), " ", convert = TRUE)



# Jeden Eintrag mehrfach listen für jede Kategorie einmal
netflix_titles %>% separate_rows(listed_in, sep = ", ")

# Jeden Eintrag mehrfach listen für jeden Schauspieler einmal
netflix_titles %>% separate_rows(cast, sep = ", ")

#Netflix Content - Movies vs. TV Shows
ggplot(data = netflix_titles, aes(x=type, fill=type))+ 
  geom_bar(color="red", size=0.4, fill="dark red")+
  labs(title ="Netflix content - Movies vs. TV Shows",x= "Content",     y="Amount")


```

